### ISSUE TITLE
تغییر تاریخ در بخش اخبار

### ISSUE THREAD

**Issue by MrAlfak** [EhsanCh/whmcs-jalalidate#1]
سلام  دوست عزیز
بنده از این سیستم استفاده می کنم در بخش اخبار در زیر خبر ها تاریخ خبر رو می زنه که می خواستم ببینم چطور می تونم تغییر بدم این بخش رو ، در حال حاظر تاریخ بصورت میلادی نمایش داده می شود .
کد استفاده شد در این بخش
`{$timestamp|date_format:"%A, %B %e, %Y"}`
اسم فایل 
`viewannouncement.tpl`
![2016-10-06_9-13-45](https://cloud.githubusercontent.com/assets/1964316/19337639/ea2fb232-9123-11e6-9683-4faa55f6a931.jpg)

**Comment by EhsanCh** [comment]
سلام
 این مورد در این افزونه پیش بینی شده و برای استفاده از آن نیاز است که در قالبتان تغییر ایجاد کنید.
در قالبتان به جای
`{$timestamp|date_format:"%A, %B %e, %Y"}`
از
`{$date}`
استفاده کنید.

**Comment by MrAlfak** [comment]
با سلام . دقیقا باید چکار کنم؟
