### ISSUE TITLE
عدم شمسی‌سازی در قسمت تیکت‌ها

### ISSUE THREAD

**Issue by reza-qalekhani** [EhsanCh/whmcs-jalalidate#3]
وقت شما بخیر
متاسفانه در نسخه آخر اسکریپت، تاریخ‌های بخش فهرست تیکت‌ها و نمایش تیکت‌ها شمسی نمیشه
ممنون میشم بررسی کنید

**Comment by EhsanCh** [comment]
در حال حاضر این پروژه فعال نیست. میتوانید از فورک هایی که دوستان توسعه داده اند استفاده کنید.
